//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrestamoDeEquipos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Prestamo
    {
        public int IdPrestamo { get; set; }
        [DisplayName("Fecha inicio de Prestamo")]
        
        public System.DateTime FechaInicio { get; set; }
        [DisplayName("Fecha fin de Prestamo")]
        
        public System.DateTime FechaFin { get; set; }
        [DisplayName("Fecha de entrega de Equipo")]
       
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<int> Multa { get; set; }
        [DisplayName("Devuelto")]
        public bool Estado { get; set; }
        [DisplayName("Usuario")]
        public int IdUsuario { get; set; }
        [DisplayName("Equipo")]
        public int IdEquipo { get; set; }

        [DisplayName("Equipo")]
        public virtual Equipo Equipo { get; set; }
        [DisplayName("Usuario")]
        public virtual Usuario Usuario { get; set; }
    }
}
